name = "worker-wandering-queen-b9d5"
main = "src/index.ts"
compatibility_date = "2024-01-22"
workers_dev = true

[[routes]]
pattern = "llama2.gitry.com"
zone_name = "gitry.com"
custom_domain = true

[ai]
binding = "AI"

[vars]
API_KEYS = ""
